/* Generated By:JavaCC: Do not edit this line. RecordGrammerConstants.java */
package biz.uro.CSVDataConverter.swing.builder.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RecordGrammerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int USETOKEN = 5;
  /** RegularExpression Id. */
  int TOSTRING = 6;
  /** RegularExpression Id. */
  int PROGRAM = 7;
  /** RegularExpression Id. */
  int DOT = 8;
  /** RegularExpression Id. */
  int HEAD = 9;
  /** RegularExpression Id. */
  int LPAREN = 10;
  /** RegularExpression Id. */
  int RPAREN = 11;
  /** RegularExpression Id. */
  int LBRACKET = 12;
  /** RegularExpression Id. */
  int RBRACKET = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int STRING = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"token\"",
    "\"toString\"",
    "\"program\"",
    "\".\"",
    "\"#\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<NUMBER>",
    "<DIGIT>",
    "<STRING>",
  };

}
